/**
 * setup-testnet.ts — Generate and fund 4 XRPL testnet accounts for Sovereign governance.
 *
 * Creates: Governance, Treasury, Stake, Business accounts.
 * Sets up multi-sign on Treasury, Stake, and Business with Governance as initial signer.
 * Saves credentials to .env.
 */

import { Client, Wallet } from 'xrpl';
import * as fs from 'fs';
import * as path from 'path';

const WSS = 'wss://s.altnet.rippletest.net:51233';
const FAUCET_URL = 'https://faucet.altnet.rippletest.net/accounts';

interface AccountInfo {
  name: string;
  envPrefix: string;
  wallet: Wallet;
  balance?: string;
}

async function fundFromFaucet(): Promise<{ address: string; seed: string; balance: number }> {
  const resp = await fetch(FAUCET_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' } });
  if (!resp.ok) throw new Error(`Faucet error: ${resp.status} ${resp.statusText}`);
  const data = await resp.json() as any;
  return {
    address: data.account.classicAddress || data.account.address,
    seed: data.seed,
    balance: data.amount,
  };
}

async function setupMultiSign(
  client: Client,
  targetWallet: Wallet,
  signerAddress: string,
  signerWeight: number = 1,
  quorum: number = 1
): Promise<string> {
  const tx = await client.submitAndWait(
    {
      TransactionType: 'SignerListSet',
      Account: targetWallet.address,
      SignerQuorum: quorum,
      SignerEntries: [
        {
          SignerEntry: {
            Account: signerAddress,
            SignerWeight: signerWeight,
          },
        },
      ],
    },
    { wallet: targetWallet }
  );
  const result = tx.result as any;
  const meta = result.meta || result.metaData;
  if (meta?.TransactionResult !== 'tesSUCCESS') {
    throw new Error(`SignerListSet failed: ${meta?.TransactionResult}`);
  }
  return result.hash;
}

async function main() {
  console.log('='.repeat(60));
  console.log('  SOVEREIGN — Testnet Account Setup');
  console.log('='.repeat(60));
  console.log();

  // 1. Fund accounts via faucet
  const accountDefs = [
    { name: 'Governance', envPrefix: 'XRPL_GOVERNANCE' },
    { name: 'Treasury', envPrefix: 'XRPL_TREASURY' },
    { name: 'Stake', envPrefix: 'XRPL_STAKE' },
    { name: 'Business', envPrefix: 'XRPL_BUSINESS' },
  ];

  const accounts: AccountInfo[] = [];

  for (const def of accountDefs) {
    console.log(`[FAUCET] Funding ${def.name} account...`);
    const funded = await fundFromFaucet();
    const wallet = Wallet.fromSeed(funded.seed);
    accounts.push({
      name: def.name,
      envPrefix: def.envPrefix,
      wallet,
    });
    console.log(`  Address: ${wallet.address}`);
    console.log(`  Seed:    ${funded.seed}`);
    console.log(`  Balance: ${funded.balance} XRP`);
    console.log();
    // Small delay between faucet requests
    await new Promise((r) => setTimeout(r, 1500));
  }

  // 2. Connect to testnet
  const client = new Client(WSS);
  await client.connect();
  console.log(`[XRPL] Connected to ${WSS}`);
  console.log();

  // 3. Wait for ledger to catch up, then verify balances
  console.log('Waiting for accounts to be confirmed on ledger...');
  await new Promise((r) => setTimeout(r, 5000));

  console.log('--- Account Balances ---');
  for (const acct of accounts) {
    const info = await client.request({
      command: 'account_info',
      account: acct.wallet.address,
      ledger_index: 'validated',
    });
    acct.balance = (Number(info.result.account_data.Balance) / 1_000_000).toFixed(2);
    console.log(`  ${acct.name}: ${acct.balance} XRP (${acct.wallet.address})`);
  }
  console.log();

  // 4. Set up multi-sign on Treasury, Stake, Business (governance as signer)
  const governance = accounts[0];
  const multisignTargets = accounts.slice(1); // Treasury, Stake, Business

  console.log('--- Multi-Sign Setup ---');
  for (const target of multisignTargets) {
    console.log(`[MULTISIGN] Setting ${governance.name} as signer on ${target.name}...`);
    try {
      const hash = await setupMultiSign(client, target.wallet, governance.wallet.address);
      console.log(`  ✓ SignerListSet tx: ${hash}`);
    } catch (err) {
      console.error(`  ✗ Failed:`, (err as Error).message);
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  console.log();

  // 5. Write .env file
  const envPath = path.join(__dirname, '..', '.env');
  const envContent = `# XRPL Configuration — Generated by setup-testnet.ts
# Generated: ${new Date().toISOString()}
XRPL_NETWORK=testnet
XRPL_WSS=${WSS}

# Governance Account
XRPL_GOVERNANCE_ADDRESS=${accounts[0].wallet.address}
XRPL_GOVERNANCE_SEED=${accounts[0].wallet.seed}

# Treasury Account (multi-sign: governance is signer)
XRPL_TREASURY_ADDRESS=${accounts[1].wallet.address}
XRPL_TREASURY_SEED=${accounts[1].wallet.seed}

# Stake Account (multi-sign: governance is signer)
XRPL_STAKE_ADDRESS=${accounts[2].wallet.address}
XRPL_STAKE_SEED=${accounts[2].wallet.seed}

# Business Account (multi-sign: governance is signer)
XRPL_BUSINESS_ADDRESS=${accounts[3].wallet.address}
XRPL_BUSINESS_SEED=${accounts[3].wallet.seed}

# Forum Storage
ARWEAVE_WALLET_PATH=
ARWEAVE_GATEWAY=https://arweave.net

# API Server
API_PORT=3000
API_HOST=0.0.0.0

# Database
DB_PATH=./data/sovereign.db
`;

  fs.writeFileSync(envPath, envContent);
  console.log(`[ENV] Written to ${envPath}`);
  console.log();

  // 6. Summary
  console.log('='.repeat(60));
  console.log('  Setup Complete!');
  console.log('='.repeat(60));
  console.log();
  for (const acct of accounts) {
    console.log(`  ${acct.name.padEnd(12)} ${acct.wallet.address}  (${acct.balance} XRP)`);
  }
  console.log();
  console.log('  Next steps:');
  console.log('    npm run dev          — Start the governance service');
  console.log('    npm run test:agent   — Run the test agent lifecycle');
  console.log();

  await client.disconnect();
}

main().catch((err) => {
  console.error('Setup failed:', err);
  process.exit(1);
});
